language: java
jdk:
- oraclejdk7
script: mvn clean install
install: true
notifications:
  email:
    recipients:
    - ybrin.development@gmail.com
    - simon.artner@gmail.com
    on_success: change
    on_failure: always
  webhooks: https://api.kwstudios.org/travis/webhooks/versions
before_deploy:
- ls
- cd target/
- ls
- cd ..
deploy:
  - provider: releases
    api_key:
      secure: MXvyvKNlEOhNV7um+lY1Np3aGmZlNvMXCsrRZBKkLs7EiSiinRWt5S4jjYwbXu/P+$
    file_glob: true
    file: ${HOME}/build/${TRAVIS_REPO_SLUG}/target/ragemode*.jar
    skip_cleanup: true
    on:
      repo: KWStudios/RageMode
      tags: true
  - provider: gcs
    access_key_id: GOOGOORZ55TL3TFGHJHZ
    secret_access_key:
      secure: i1cuqczKWqYeoYlGlwdIJFoTTRwKJn5NZUq/OoLsqtRgjdIY41zKmZMM3Epe+c1Hl5iY7DzKDWhAbZJCOLeUDkPJC7SbgvLNEpWQd39iJGo9rhn3aa+IzN/JxKUItYdYKsx/yqbwXdnbOm/Pt+7dNhCfkj04FgJX8QrXqtuT2pBZj0oDXa9NAq5277EDB41UqqIQwdMJgbsk6XMW/uPF+VeWr4SJbbX6902t7v+LKfPyVUUuhDNVFeFHPQ6LIg2FArtDYsg8evTOIJ6Uk6lv/XvbewR7LJoN6SBMAcYiKz12tBIi71Ij4vU1UDJ6ixHlFk7P85ip2rt1xBAL0JTUayDMYp6NGjW2mCv9mJjvie9YbSv8m8brevwbT7hLFvsO33WOR98BnEFr7yYGNOPv0bGvWIBQmk8tQQjDc3K5sDg7JevWVt5u/wgV13ZRDCkEgCTqGhseXS7D5rFhe6HpuD6ZHuEcnalhi+zz8Ua7pwm9UwYPuZQdKK2rilU8LfK2qyDEGbQNGcfuyNtPxptvz2Jwo/F2QF3AaytV7/7hX12VxlviwUOV5KCbLZcRb1W5ry45LAPYi0k14Vky+WhK/VUIbgUYIO8ohiiyHhmtbvYkGGegVlmVGJfJ/owAp8qBh50QebRWU76oWSC/MW5oZeNs052ySmd6uC565YuvBSM=
    file_glob: true
    bucket: play-kwstudios-org
    local-dir: "${HOME}/build/${TRAVIS_REPO_SLUG}/target"
    upload-dir: ragemode/travis-builds/${TRAVIS_BUILD_NUMBER}
    skip_cleanup: true
    acl: public-read
    on:
      repo: KWStudios/RageMode
