language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
script: mvn test
install: true
notifications:
  email:
    recipients:
      - "ybrin.development@gmail.com"
      - "simon.artner@gmail.com"
    on_success: change
    on_failure: always
