name: RageMode
main: org.kwstudios.play.ragemode.loader.PluginLoader
version: v0.1-alpha

commands:
  rm:
    description: Main command.
    aliases: ['ragemode']
    permission: ragemode.rm
    permission-message: You may not use that command!
  rm add:
    description: Adds a RageMode map with the given name and the maximum player count.
    aliases: ['ragemode add']
    permission: ragemode.admin.add
    permission-message: You may not use that command!
  rm lobby:
    description: Sets the lobby for the given RageMode map to the current position.
    aliases: ['ragemode lobby']
    permission: ragemode.admin.lobby
    permission-message: You may not use that command!
  rm addspawn:
    description: Sets a spawn location for the given RageMode map to the current position.
    aliases: ['ragemode addspawn']
    permission: ragemode.admin.addspawn
    permission-message: You may not use that command!
  rm remove:
    description: Removes the given RageMode map.
    aliases: ['ragemode remove']
    permission: ragemode.admin.remove
    permission-message: You may not use that command!
  rm stop:
    description: Stops the given RageMode map.
    aliases: ['ragemode stop']
    permission: ragemode.admin.stop
    permission-message: You may not use that command!
  rm join:
    description: Joins the given RageMode game.
    aliases: ['ragemode join']
    permission: ragemode.rm.join
    permission-message: You may not use that command!
  rm leave:
    description: Leaves the current RageMode game.
    aliases: ['ragemode leave']
    permission: ragemode.rm.leave
    permission-message: You may not use that command!
  rm list:
    description: Lists all RageMode maps.
    aliases: ['ragemode list']
    permission: ragemode.rm.list
    permission-message: You may not use that command!
  rm reload:
    description: Reloads the config.yml from disk.
    aliases: ['ragemode reload']
    permission: ragemode.admin.reload
    permission-message: You may not use that command!
    
permissions:
    ragemode.rm:
        description: Gives access to the main command.
        default: true
    ragemode.rm.*:
        description: Gives access to all basic commands.
        default: true
        children:
            ragemode.rm.join: true
            ragemode.rm.leave: true
            ragemode.rm.list: true
    ragemode.admin.*:
        description: Gives access to all game-setup commands.
        default: op
        children:
            ragemode.admin.add: true
            ragemode.admin.lobby: true
            ragemode.admin.addspawn: true
            ragemode.admin.remove: true
            ragemode.admin.reload: true
            ragemode.admin.stop: true
    