# Default language. Example: en, hu, de etc.
# You can find all supported languages on: https://github.com/montlikadani/RageMode/wiki/Languages
language: en

# Statistic types: yaml, mysql
statistics: yaml

# Logging console messages, such as error description
log-console: false

# This saves the player datas, such as inventory, effects etc. to a file.
# This can be useful for a random server shutdown.
# If this false and "require-empty-inventory-to-join" also false then the players 
# loses his items from inventory.
# If this is false, we still need some data to save that will not cause any problems 
# at the end of the game.
save-player-datas-to-file: false

# Require empty inventory to join to game?
# If this false and "save-player-datas-to-file" also false then the players 
# loses his items from inventory.
require-empty-inventory-to-join: true

# bStats metrics for sending some statistic.
metrics: true

# Hook into bungee
# For server game join signs use:
# https://www.spigotmc.org/resources/37446/
bungee:
  enable: false
  # Bungeecord server name when the game end and teleport players to this server.
  hub-name: "lobby"

# MySQL database to save the players statistic.
MySQL:
  auto-reconnect: false
  use-SSL: true
  username: accountname
  password: password
  database: database
  host: localhost
  port: "3306"
  table-prefix: rm_
  use-unicode: true
  verify-server-certificate: false
  character-encoding: "UTF-8"

# Sign texts
signs:
  # Enables the signs creates.
  enable: false

  # Sign refresh time in seconds.
  update-time: 20

  # Sign text when the game running or waiting for players.
  game:
    running: "&6&oRunning..."
    waiting: "&cWaiting..."
    full: "&4FULL"
    locked: "&9Locked"

  # Sign text list (max. 4 line)
  # Use %game%, %current-players%, %max-players%, %running% placeholder.
  list:
  - "&3[&5RageMode&3]"
  - "&a%game%"
  - "&ePlayers&3 [%current-players%/%max-players%&3]"
  - "%running%"

  # Defines a background of the sign.
  background:
    enable: false
    # Possible types: glass, wool, terracotta (clay)
    type: glass

# Actionbar messages
actionbar-messages:
  join:
    # Actionbar message when started the game and sends to player.
    # This be ignored, when empty or not found.
    message: ""

# Bossbar messages
bossbar-messages:
  join:
    # Bossbar message when started the game and sends to player.
    # This be ignored, when empty or not found.
    message: "&bWelcome&a %player%&b to the&c %game%&b game!"

    # Bossbar style
    # Styles: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html
    style: "SEGMENTED_6"

    # Bossbar color
    # Colors: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
    color: GREEN

# Title texts
titles:
  # When a player join to the game, and send title for him.
  join-game:
    title: "&e%game%"
    subtitle: "&3by yourname"
    # The time it takes for the title to fade into the screen. (In ticks)
    fade-in: 20
    # The time it takes for the title to stay on the screen. (In ticks)
    stay: 50
    # The time it takes for the title to fade out of the screen. (In ticks)
    fade-out: 20

  # Lobby waiting timer title.
  lobby-waiting:
    enable: true
    title: ""
    subtitle: "&9%time%"
    fade-in: 10
    stay: 30
    fade-out: 10
    # Intervals when the lobby timer reaches e.g. 5 intervals, then send it on the screen.
    values-to-send-start-message: [5, 4, 3, 2, 1]

  # When a player won a game, and send title for all players that in the game currently.
  player-won:
    title: "&2Congratulations!"
    subtitle: "&e%winner%&6 won this round!"
    fade-in: 20
    stay: 80
    fade-out: 20

  # When you won a game, and send title for him that in the game currently.
  you-won:
    title: "&aCongratulations!"
    subtitle: "&2You won this round!"
    fade-in: 20
    stay: 80
    fade-out: 20

# Enables the spectator mode in the already running game, to see what happens in that game.
spectator:
  enable: true

  # Which spectator commands will be allowed  to use in-game?
  allowed-spectator-commands:
  - "/rm leave"
  - "/ragemode leave"

# Global settings for game.
game:
  # ---- Attention! The games spawn, lobby locations are not configured in this place! ----
  global:
    # Lobby settings
    lobby:
      # Minimum players to start the lobby timer.
      # If this is less than 1, then 2 defaults.
      min-players-to-start-lobby-timer: 2

      # Lobby delay to start the game in seconds.
      delay: 30

      # Sending lobby waiting message to start game in seconds.
      time-to-send-message: 9

      # Should be enable chat in lobby?
      # This ignores with ragemode.bypass.lobby.lockchat permission.
      enable-chat-in-lobby: true

      # Does count the player's level with the start time of the game in the lobby?
      player-level-as-time-counter: false

      # Time intervals when the lobby timer reaches, for example, 10 seconds,
      # write it into the chat.
      values-to-send-start-message: [30, 20, 10, 5, 4, 3, 2, 1]

    # Death messages
    # This ignores, when the boolean is contains in the arenas file.
    death-messages: true

    # If this false if player has fallen to ground then not damage.
    damage-player-fall: false

    # Show the player name above player head.
    # This makes the game more difficult, because if it is enabled, it hides the names of 
    # the players if the target player is not in the position of the other player's 10 radius eye.
    show-name-above-player-when-look: true

    # When the game is over, the players will freeze (if the game mode is not in spectator),
    # then if the time expires, it will be automatically returned to the set location.
    # This ignores the winner player.
    # Counting in seconds!
    game-freeze-time-at-end-game: 10

    # Should be enable chat in the game?
    # This ignores with ragemode.bypass.game.lockchat permission.
    enable-chat-in-game: true

    # Defaults values when in the setup not specify e.g bossbar.
    defaults:
      # Bossbar messages when a player killed someone.
      # This ignores, when the boolean is contains in the arenas file.
      bossbar: false

      # Actionbar messages when a player get points or killed someone.
      # This ignores, when the boolean is contains in the arenas file.
      actionbar: true

      # Game time in minutes.
      # This ignores, when the integer is contains in the arenas file.
      gametime: 10

    # Switch the game mode to spectator when the game is end?
    # Ignores the winner player.
    switch-gamemode-to-spectator-at-end-of-game: true

    # Enables the chat after end of game.
    enable-chat-after-end: true

    # Tablist formatting.
    tablist:
      # Player prefix/suffix format to show example the player kills, deaths etc.
      player-format:
        enable: false
        prefix: ""
        suffix: "&e %kills%"
      # Tablist header/footer formats.
      list:
        enable: false
        header:
        - "&cRage&bMode&e minigame stats"
        - "&aYour kills/deaths:&e %kd%"
        footer:
        - "&6Points:&e %points%"

    # Displays the score board on the right screen.
    scoreboard:
      enable: true
      title: "&6RageMode"
      content:
      - ""
      - "&7------"
      - "&aPoints:&e %points%"
      - ""
      - "&5Wins:&e %wins%"
      - "&7------"
      - ""

    # Chat format
    chat-format:
      enable: false
      format: "&e[%points%]&r %player%&7:&r %message%"

    # In-game commands, to use a player the specified commands in-game.
    allowed-commands:
    - "/rm leave"
    - "/ragemode leave"
    - "/ragemode stop"

    # Execute commands when the player left the game while playing. (Only console commands)
    # # Use %player%, %player-ip% placeholder.
    run-commands-for-player-left-while-playing:
    #- "tell %player% &cWhy you left from the game while playing?"

# Grant rewards at end of game.
# Rewards can be found in the rewards.yml file.
rewards:
  enable: true

# Points for killing or deaths.
points:
  bowkill: 25
  axekill: 30
  axedeath: -50
  knifekill: 15
  explosionkill: 25
  # If 0 ignoring the loss.
  suicide: -20

# Item editing (name, lore, slot)
# Inventory positions here: http://redditpublic.com/images/b/b2/Items_slot_number.png
items:
  leavegameitem:
    item: BARRIER
    name: "&cExit from the game"
    lore:
    - "&7&oLeft/rigth click"
    slot: 5
  force-start:
    item: LEVER
    name: "&2Force the game start"
    lore:
    - "&7&oLeft/rigth click"
    slot: 3
  rageBow:
    name: "&4Rage Bow"
    lore:
    - "&7One shot, headshot & explosion"
    slot: 0
  rageKnife:
    name: "&6Rage&4 Knife"
    lore:
    - "&7One hit, dead."
    slot: 1
  combatAxe:
    name: "&6CombatAxe"
    lore:
    - "&7Right click, throws a axe and dead"
    slot: 2
  rageArrow:
    name: "&7Rage Arrow"
    slot: 9
  grenade:
    name: "&7Grenade"
    lore:
    - "&7Right click, throws a grenade and boom!"
    slot: 5

# Do NOT edit this!!!
config-version: 1.0
